package:
  name: pscondaenvs
  version: "1.0.0"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  path: ./

about:
  home: https://github.com/BCSharp/PSCondaEnvs
  license: MIT
  license_file: LICENSE